//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaPlayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Form_Main_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form_Main_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaPlayer.Form_Main ", typeof(Form_Main_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation1_BlindCoeff {
            get {
                object obj = ResourceManager.GetObject("animation1.BlindCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation1_MosaicCoeff {
            get {
                object obj = ResourceManager.GetObject("animation1.MosaicCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation1_MosaicShift {
            get {
                object obj = ResourceManager.GetObject("animation1.MosaicShift", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation1_ScaleCoeff {
            get {
                object obj = ResourceManager.GetObject("animation1.ScaleCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        internal static System.Drawing.PointF animation1_SlideCoeff {
            get {
                object obj = ResourceManager.GetObject("animation1.SlideCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Redo_Image {
            get {
                object obj = ResourceManager.GetObject("Button_Redo.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gunaButton_Home_Image {
            get {
                object obj = ResourceManager.GetObject("gunaButton_Home.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gunaButton_Home_OnHoverImage {
            get {
                object obj = ResourceManager.GetObject("gunaButton_Home.OnHoverImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gunaButton_Library_Image {
            get {
                object obj = ResourceManager.GetObject("gunaButton_Library.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gunaButton_Library_OnHoverImage {
            get {
                object obj = ResourceManager.GetObject("gunaButton_Library.OnHoverImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gunaButton_Music_Image {
            get {
                object obj = ResourceManager.GetObject("gunaButton_Music.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gunaButton_Music_OnHoverImage {
            get {
                object obj = ResourceManager.GetObject("gunaButton_Music.OnHoverImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gunaButton_Search_Image {
            get {
                object obj = ResourceManager.GetObject("gunaButton_Search.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gunaButton_Search_OnHoverImage {
            get {
                object obj = ResourceManager.GetObject("gunaButton_Search.OnHoverImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gunaButton_Settings_Image {
            get {
                object obj = ResourceManager.GetObject("gunaButton_Settings.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gunaButton_Settings_OnHoverImage {
            get {
                object obj = ResourceManager.GetObject("gunaButton_Settings.OnHoverImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gunaButton_Video_Image {
            get {
                object obj = ResourceManager.GetObject("gunaButton_Video.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gunaButton_Video_OnHoverImage {
            get {
                object obj = ResourceManager.GetObject("gunaButton_Video.OnHoverImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_Image {
            get {
                object obj = ResourceManager.GetObject("Logo.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
